//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Hackathon.Website.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeatmapDatapoint
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string RelativeUrl { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Width { get; set; }
    }
}
